### ISSUE TITLE
New build strategy

### ISSUE THREAD

**Issue by matterhorn103** [flathub/org.openchemistry.Avogadro2#173]
@kevinsmia1939 This is mostly to discuss with you the build strategy for the flatpak going forwards. :)

You have maintained this flatpak for a while, and in general you have significantly more experience packaging flatpaks than I do, so I am very keen to have your feedback and opinions on the changes I've made and am proposing!

What I'd really like is for the flatpak to become the primary version we recommend to Linux users over the AppImage (though that wouldn't be deprecated). I don't think you're someone who needs convincing of flatpak's advantages, haha.

For this to happen we need a couple of things:

1. It has to be the most stable version on Linux
2. The environment it runs in and the way it is built needs to match or be very similar to the native Linux, Windows, and macOS versions so that bugs are representative rather than specific to the platform
3. We need a cutting-edge version that can be given to users who are encountering difficulties with the last point release or who need new features, as that is generally the first thing Geoff suggests to people who raise issues on the forum

Given the issues we have had and are having with the AppImage, primarily due to the fact that AppImage's don't bundle everything, just some things, I see 1) as fairly easily achievable if a bit of time and care is invested.

As you've seen I have been working on a beta build that should stay close (within ~1 week) of the nightly in order to fulfil 3). Happily, it's now uploaded and can be obtained from the flathub-beta repo.

I don't know if you took a look at the actual changes, but while doing that I completely overhauled the manifest so that the build relies primarily on the upstream build process rather than compiling individual components itself, in order to fulfil 2). Once this manifest is proven to work, I'd like to use it (with the release commits) for the `stable` branch too.

We also plan to add a flatpak build (to a bundle) to Avogadro's CI workflow too, and the manifest will be used for that too. Having flatpak in the continuous testing regime will help a lot towards 1).

I have two questions/proposals that I'd like your input on.

---

In order to match the build process for the other Linux builds, I wanted to review the CMake flags that are being used. In the old manifest you are passing a lot of flags:

- avogadrolibs
  - `-DOpenGL_GL_PREFERENCE=GLVND` **Not valid option?**
  - `-DUSE_SYSTEM_GENXRDPATTERN:BOOL=ON` **matches default**
  - `-DCMAKE_BUILD_TYPE:STRING=Release` **matches master**
  - `-DENABLE_TRANSLATIONS:BOOL=ON` **different to master (off by default)**
  - `-DUSE_HDF5:BOOL=ON` **different to upstream (off by default)**
  - `-DUSE_PYTHON:BOOL=ON` **different to upstream (off by default)**
  - `-DUSE_QT:BOOL=ON` **matches default**
  - `-DUSE_LIBMSYM:BOOL=ON` **matches default**
  - `-DUSE_SPGLIB:BOOL=ON` **matches default**
  - `-DUSE_MMTF:BOOL=ON` **matches default**
  - `-DUSE_VTK:BOOL=ON` **matches upstream**
  - `-DBUILD_GPL_PLUGINS:BOOL=ON` **matches upstream**
  - `-DBUILD_STATIC_PLUGINS:BOOL=ON` **matches default**
  - `-DENABLE_TESTING:BOOL=OFF` **matches default**
  - `-DOpenBabel3_INCLUDE_DIR=/app/include/openbabel3` **?**
- avogadroapp
  - `-DENABLE_RPATH:BOOL=ON` **matches default**
  - `-DENABLE_TESTING:BOOL=OFF` **matches default**
  - `-DBUILD_DOCUMENTATION:BOOL=OFF` **matches default**
  - `-DCMAKE_BUILD_TYPE:STRING=Release` **matches upstream**
  - `-DEIGEN3_INCLUDE_DIR=/app/include/eigen3` **?**
 
You also build `molequeue`, which is no longer being built upstream because it is unmaintained and is unlikely to see a port to Qt6 in the near future.

Meanwhile the upstream AppImage builds use only:

- `-DBUILD_GPL_PLUGINS=ON`
- `-DWITH_COORDGEN=OFF`
- `-DUSE_VTK=ON`
- `-DBUILD_MOLEQUEUE=OFF`
- `-DINSTALL_BUNDLE_FILES=ON`

So to begin with I have stuck to just those flags, plus `-DDOWNLOAD_TO_SOURCE_DIR=ON` to make the offline build from source work and `-DQT_VERSION=6` for the Qt upgrade. I have also left out `-DWITH_COORDGEN=OFF` because that's off by default. I am waiting to work out whether we need `-DINSTALL_BUNDLE_FILES=ON`, because the old flatpak doesn't use it.

Now I'd like to work out what other flags from the manifest currently used for `stable` need to be added, if any. Many of the flags you used match the default, so I think they should definitely be left out - that way, should the upstream default change, it will automatically be adopted in the flatpak without manual intervention necessary. Of the others, it's not always clear to me why you used them.

It'd be a real help to me if you could explain why you originally used the following flags that don't match the default/upstream:

- Different to the default or the upstream, and I don't know why:
  - `-DENABLE_TRANSLATIONS:BOOL=ON`
  - `-DUSE_HDF5:BOOL=ON`
  - `-DUSE_PYTHON:BOOL=ON`
- Possibly no longer necessary now that Avogadro builds the dependencies itself:
  - `OpenBabel3_INCLUDE_DIR`
  - `EIGEN3_INCLUDE_DIR`

That way we can hopefully work out whether they are still needed or not.

---

One further change I'd like to make to the way you and I maintain the flatpak, if you're ok with it, is to stick to the versions of the third-party dependencies that upstream uses. Currently this is not the case; the cross-checker is set up to look for newer versions of the flatpak's dependencies, and you generally merge the pull requests (as long as they don't fail), which means that the codebase has diverged from the other binary builds of Avogadro that are distributed.

I feel like this is a potential source of bugs that we don't otherwise test for, and a barrier to support because the platform has then diverged from all other platforms. So in the interests of striving for 1) and 2) I think it is best to no longer change the dependency versions independently of upstream.

Having said that, I do agree that more up-to-date dependencies should be used, but that is IMO better changed upstream. In general I have shifted as much as possible out of the flathub repo and to upstream, such as the metadata file; I think that's a better approach and matches the flathub guidelines. What do you think?

**Comment by matterhorn103** [comment]
Oh and one further question: the old manifest also builds `zeromq` -- can you remember what for?

**Comment by ghutchis** [comment]
`zeromq` was an optional dependency for `MoleQueue`

**Comment by kevinsmia1939** [comment]
Hi @matterhorn103 
Some of the build flag that was enable on Flatpak build that is not enable by default on the default is because I just want to provide as much features as possible for the end user. It depends on who you ask, generally in my experience, some flag are disabled because it would took a long time to compile or not often use by the end user, but here since the end user are not compiling them, I imagine that I will just try to enable them all. If the end user will use it or not it is up to them. 
The practice of building external modules rather than bundled dependencies are from my experience with maintaining package on openSUSE that has practice to prefer external dependencies. But since this is Flatpak, I believe you can remove them and use bundled deps.

I am not aware if molecule is use, if not just remove it.
As for the eigen and openbabel include flag, it does not compile if not set iirc.

-DOpenGL_GL_PREFERENCE=GLVND is from long ago when I just copy the build manifest from else where. Feel free to remove if not needed.

I don't have much time as before now. So feel free to work on this as much as you would like.

**Comment by matterhorn103** [comment]
Ok, thanks for your insights. In that case I do think it's best to mirror the upstream builds as much as possible.

The openSUSE build, and presumably other distro packages of Avo, has things like the Python bindings as an optional separate package. Since Flatpak supports extensions to apps, maybe at some point I'll take a look at that for providing the extended functionality. If `molequeue` some day gets resurrected it would also be a good way to add that.

The beta is now in a state I'm pretty happy with, with all the immediately obvious issues ironed out (other than an Open Babel issue that doesn't seem restricted to the Flatpak). And that despite it building against Qt6. So for the next point release of Avogadro I'll merge `beta` into `stable` and use the new build strategy for `stable` as well from then on.

I think trying to use the new manifest earlier than that for the 1.99 build would be a waste of energy, as it would require patching of the 1.99 source with the recent commits that had fixes aimed at the Flatpak, and the current `stable` build works mostly fine.
